### ISSUE TITLE
Weight factors for soil moisture prediction

### ISSUE THREAD

**Issue by Kallorian** [bcgov/bcgov-r-geo-workshop#20]
This is an issue I'm working on for my Master's research. I have datasets and variables available, but I'm unsure how to work this bit of coding.

**Comment by boshek** [comment]
Thanks for this @Kallorian . Can you provide a little more information about what it is your hoping to work on in the hackathon? This will help other people decide if this is something they would also like to work on.

**Comment by Kallorian** [comment]
The project is working with a LiDAR derived DEM and a series of ground truth data, trying to create a prediction methodology for finding soil moisture regime. A basic equations already exists for this project, combining several covariates derived from the DEM. The objective is to find a way to calculate weights for the covariates in the equation based on the available data. 

(I'm currently having difficulties getting to my data, but that should be solved by friday)

**Comment by Kallorian** [comment]
Issues getting data to work with for this project were unfortunately not resolved so this would not be a good project today.
