### ISSUE TITLE
Create common data folder

### ISSUE THREAD

**Issue by ateucher** [bcgov/bcgov-r-geo-workshop#6]
To make it easy for users to get data they will need for the course, we should make a single `data/` folder in this repo, different instructors can put all their data in there, but can put it in a subfolder if they wish

**Comment by ateucher** [comment]
This way we can leverage `usethis::use_course("bcgov/bcgov-r-geo-workshop")`

**Comment by gcperk** [comment]
I created a data folder and subfolder for Day 2 (AM and PM) matching the folder names. Feel free to adjust if needed.

**Comment by ateucher** [comment]
I think that looks perfect, thanks Gen!
